# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Dan Irons
tagline:          'A data guy'
description:      '¯\_(ツ)_/¯'
# url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Dan Irons'
  url:            https://twitter.com/_Dan_Irons

paginate:         5

# Custom vars
# version:          2.1.0

github:           
  repo:           https://github.com/iron0012
